"""empty message

Revision ID: 8a299a100c61
Revises: a70fd690e30e
Create Date: 2020-06-17 16:13:53.160435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a299a100c61'
down_revision = 'a70fd690e30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue_description', sa.String(length=128), nullable=True))
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_talent')
    op.add_column('venues', sa.Column('seeking_talent_description', sa.String(length=128), nullable=True))
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('venues', 'seeking_talent_description')
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_venue_description')
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
