"""empty message

Revision ID: d7b58f0d7028
Revises: 8a299a100c61
Create Date: 2020-06-17 18:56:31.316732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b58f0d7028'
down_revision = '8a299a100c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('posting_date_venue', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'posting_date_venue')
    # ### end Alembic commands ###
